import { useState } from 'react'
import { PageHeader } from '../components/PageHeader'
import { DeleteInvoiceConfirmModal } from '../components/DeleteInvoiceConfirmModal'
import { useCustomerDebts } from '../hooks/useCustomerDebts'
import { useCustomers } from '../hooks/useCustomers'
import { useInvoices } from '../hooks/useInvoices'
import type { Payment } from '../types/invoice'
import { todayIso } from '../utils/id'
import { formatVnd, parseNumber } from '../utils/money'

interface Props { customerId: string; onBack: () => void; onOpenInvoice: (id: string) => void }

export function CustomerDetailPage({ customerId, onBack, onOpenInvoice }: Props) {
  const { customers } = useCustomers(); const { invoices, payments, addPayment, deleteInvoice } = useInvoices(); const { debts: storedDebts, addDebt, payDebt } = useCustomerDebts()
  const customer = customers.find(item => item.customerId === customerId); const mine = invoices.filter(item => item.customerId === customerId && item.status !== 'bombed').sort((a, b) => b.invoiceDate.localeCompare(a.invoiceDate) || b.createdAt.localeCompare(a.createdAt)); const invoiceDebts = mine.filter(invoice => invoice.remaining > 0); const manualDebts = storedDebts.filter(debt => debt.customerId === customerId && debt.remaining > 0).sort((a, b) => b.debtDate.localeCompare(a.debtDate) || b.createdAt.localeCompare(a.createdAt))
  const [showPayment, setShowPayment] = useState(false); const [showDebtForm, setShowDebtForm] = useState(false); const [deleteInvoiceId, setDeleteInvoiceId] = useState<string | null>(null); const [showQuantity, setShowQuantity] = useState(true); const [amount, setAmount] = useState(''); const [debtAmount, setDebtAmount] = useState(''); const [date, setDate] = useState(todayIso()); const [debtDate, setDebtDate] = useState(todayIso()); const [method, setMethod] = useState<Payment['paymentMethod']>('transfer'); const [note, setNote] = useState(''); const [debtNote, setDebtNote] = useState(''); const [error, setError] = useState('')
  if (!customer) return <><button className="back-btn" onClick={onBack}>← Quay lại</button><p>Không tìm thấy khách hàng.</p></>
  const quantity = mine.reduce((sum, invoice) => sum + invoice.items.reduce((itemSum, item) => itemSum + item.quantity, 0), 0), total = mine.reduce((sum, invoice) => sum + invoice.subtotal, 0), paid = mine.reduce((sum, invoice) => sum + invoice.deposit + invoice.paid, 0), invoiceDebtTotal = invoiceDebts.reduce((sum, invoice) => sum + invoice.remaining, 0), manualDebtTotal = manualDebts.reduce((sum, debt) => sum + debt.remaining, 0), totalDebt = invoiceDebtTotal + manualDebtTotal
  const savePayment = () => { const value = parseNumber(amount); if (!value || value < 0) return setError('Nhập số tiền thanh toán hợp lệ.'); if (value > totalDebt) return setError(`Số tiền không được lớn hơn tổng công nợ ${formatVnd(totalDebt)}.`); let remainder = value; [...invoiceDebts].sort((a,b) => a.invoiceDate.localeCompare(b.invoiceDate) || a.createdAt.localeCompare(b.createdAt)).forEach(invoice => { const applied = Math.min(remainder, invoice.remaining); if (applied > 0) { addPayment({ customerId, invoiceId: invoice.invoiceId, amount: applied, paymentDate: date, paymentMethod: method, note: note || 'Thanh toán công nợ tổng' }); remainder -= applied } }); [...manualDebts].sort((a,b) => a.debtDate.localeCompare(b.debtDate) || a.createdAt.localeCompare(b.createdAt)).forEach(debt => { const applied = Math.min(remainder, debt.remaining); if (applied > 0) { payDebt(debt.debtId, applied); remainder -= applied } }); setShowPayment(false); setAmount(''); setNote(''); setError('') }
  const saveDebt = () => { const value = parseNumber(debtAmount); if (!value || value < 0) return setError('Nhập số tiền nợ hợp lệ.'); addDebt({ customerId, amount: value, debtDate, note: debtNote.trim() }); setShowDebtForm(false); setDebtAmount(''); setDebtNote(''); setError('') }
  const removeInvoice = () => { if (!deleteInvoiceId) return; deleteInvoice(deleteInvoiceId); setDeleteInvoiceId(null) }
  return <><button className="back-btn" onClick={onBack}>← Khách hàng</button><PageHeader title={customer.name} subtitle={customer.address || 'Chưa có địa chỉ'} />
    <div className="metric-grid"><article className="metric-card"><span>Đã lấy <button className="inline-visibility-button" onClick={() => setShowQuantity(!showQuantity)}>{showQuantity ? 'Ẩn' : 'Hiện'}</button></span><strong>{showQuantity ? `${quantity} đôi` : '••• đôi'}</strong></article><article className="metric-card"><span>Còn nợ</span><strong>{formatVnd(totalDebt)}</strong></article></div>
    <section className="form-card"><div className="totals-row light"><span>Tổng tiền hàng</span><strong>{formatVnd(total)}</strong></div><div className="totals-row light"><span>Đã thanh toán</span><strong>{formatVnd(paid)}</strong></div>{manualDebtTotal > 0 && <div className="totals-row light"><span>Công nợ ghi tay</span><strong className="debt">{formatVnd(manualDebtTotal)}</strong></div>}</section>
    <button className="secondary-button" onClick={() => { setShowDebtForm(!showDebtForm); setError('') }}>{showDebtForm ? 'Đóng ghi nợ' : 'Tạo công nợ'}</button>
    {showDebtForm && <section className="form-card payment-form"><div className="form-card-heading"><h2>Ghi nợ cho khách</h2></div><label className="field"><span className="field-label">Số tiền nợ</span><input type="number" min={1} inputMode="numeric" value={debtAmount} onChange={event => setDebtAmount(event.target.value)} /></label><label className="field"><span className="field-label">Ngày ghi nợ</span><input type="date" value={debtDate} onChange={event => setDebtDate(event.target.value)} /></label><label className="field"><span className="field-label">Ghi chú</span><input value={debtNote} onChange={event => setDebtNote(event.target.value)} placeholder="Ví dụ: Bán thiếu, chưa lập hóa đơn" /></label>{error && <div className="error-banner">{error}</div>}<button className="primary-button" onClick={saveDebt}>Lưu công nợ</button></section>}
    {totalDebt > 0 && <><button className="primary-button" onClick={() => { setShowPayment(!showPayment); setError('') }}>Thanh toán tổng công nợ</button>{showPayment && <section className="form-card payment-form"><div className="form-card-heading"><h2>Thanh toán tổng công nợ</h2></div><div className="debt-summary">Tổng công nợ hiện tại: <strong>{formatVnd(totalDebt)}</strong><span>Tiền được phân bổ vào hóa đơn cũ nhất, rồi đến khoản ghi nợ.</span></div><label className="field"><span className="field-label">Số tiền thanh toán</span><input type="number" min={1} max={totalDebt} inputMode="numeric" value={amount} onChange={event => setAmount(event.target.value)} /></label><label className="field"><span className="field-label">Ngày thanh toán</span><input type="date" value={date} onChange={event => setDate(event.target.value)} /></label><div className="segmented"><button className={method === 'transfer' ? 'active' : ''} onClick={() => setMethod('transfer')}>Chuyển khoản</button><button className={method === 'cash' ? 'active' : ''} onClick={() => setMethod('cash')}>Tiền mặt</button></div><label className="field"><span className="field-label">Ghi chú</span><input value={note} onChange={event => setNote(event.target.value)} placeholder="Không bắt buộc" /></label>{error && <div className="error-banner">{error}</div>}<button className="primary-button" onClick={savePayment}>Lưu thanh toán</button></section>}</>}
    {manualDebts.length > 0 && <section className="form-card"><div className="form-card-heading"><h2>Công nợ ghi tay</h2><strong className="debt">{formatVnd(manualDebtTotal)}</strong></div>{manualDebts.map(debt => <div className="invoice-line" key={debt.debtId}><div><strong>{debt.note || 'Khoản ghi nợ'}</strong><span>{debt.debtDate} · Còn {formatVnd(debt.remaining)}</span></div><strong className="debt">{formatVnd(debt.remaining)}</strong></div>)}</section>}
    <section className="form-card"><div className="form-card-heading"><h2>Lịch sử lấy hàng</h2></div>{mine.map(invoice => <div className="history-row" key={invoice.invoiceId}><button className="history-open" onClick={() => onOpenInvoice(invoice.invoiceId)}><div><strong>{invoice.invoiceId}</strong><span>{invoice.invoiceDate} · {invoice.items.reduce((sum, item) => sum + item.quantity, 0)} đôi</span></div><div><strong>{formatVnd(invoice.subtotal)}</strong><span className={invoice.remaining ? 'debt' : 'settled'}>{invoice.remaining ? `Nợ ${formatVnd(invoice.remaining)}` : 'Đã đủ'}</span></div></button><button className="list-delete-button" onClick={() => setDeleteInvoiceId(invoice.invoiceId)} aria-label={`Xóa ${invoice.invoiceId}`}>Xóa</button></div>)}</section>{deleteInvoiceId && <DeleteInvoiceConfirmModal invoiceId={deleteInvoiceId} onCancel={() => setDeleteInvoiceId(null)} onConfirm={removeInvoice} />}
    <section className="form-card"><div className="form-card-heading"><h2>Lịch sử thanh toán</h2></div>{payments.filter(payment => payment.customerId === customerId).sort((a, b) => b.paymentDate.localeCompare(a.paymentDate) || b.createdAt.localeCompare(a.createdAt)).map(payment => <div className="invoice-line" key={payment.paymentId}><div><strong>{payment.kind === 'deposit' ? 'Đặt cọc' : 'Thanh toán'}</strong><span>{payment.paymentDate}{payment.note ? ` · ${payment.note}` : ''}</span></div><strong>{formatVnd(payment.amount)}</strong></div>)}</section>
  </>
}
