import { useMemo, useState } from 'react'
import { PageHeader } from '../components/PageHeader'
import { useCustomerDebts } from '../hooks/useCustomerDebts'
import { useInvoices } from '../hooks/useInvoices'
import { useSettings } from '../hooks/useSettings'
import { useSupplierPayments } from '../hooks/useSupplierPayments'
import { todayIso } from '../utils/id'
import { formatVnd, parseNumber } from '../utils/money'

export function SupplierDebtPage() {
  const { settings } = useSettings(); const { invoices } = useInvoices(); const { debts } = useCustomerDebts()
  const { suppliers, payments, debtEntries, addSupplier, addPayment, addDebtEntry } = useSupplierPayments()
  const [showSupplierForm, setShowSupplierForm] = useState(false); const [showPaymentForm, setShowPaymentForm] = useState(false); const [showDebtForm, setShowDebtForm] = useState(false); const [name, setName] = useState(''); const [openingDebt, setOpeningDebt] = useState(''); const [rate, setRate] = useState(String(settings.exchangeRate)); const [supplierId, setSupplierId] = useState(''); const [paymentNdt, setPaymentNdt] = useState(''); const [debtNdt, setDebtNdt] = useState(''); const [note, setNote] = useState(''); const [debtNote, setDebtNote] = useState(''); const [error, setError] = useState('')
  const customerDebt = invoices.filter(invoice => invoice.status !== 'bombed').reduce((sum, invoice) => sum + invoice.remaining, 0) + debts.reduce((sum, debt) => sum + debt.remaining, 0)
  const supplierRows = useMemo(() => suppliers.map(supplier => { const mine = payments.filter(payment => payment.supplierId === supplier.supplierId); const additions = debtEntries.filter(entry => entry.supplierId === supplier.supplierId); const addedNdt = additions.reduce((sum, entry) => sum + entry.amountNdt, 0); const paidNdt = mine.reduce((sum, payment) => sum + (payment.amountNdt ?? payment.amount / (payment.exchangeRate || supplier.exchangeRate)), 0); const remainingNdt = Math.max(0, supplier.openingDebtNdt + addedNdt - paidNdt); return { supplier, addedNdt, paidNdt, remainingNdt, remainingVnd: remainingNdt * supplier.exchangeRate } }), [suppliers, payments, debtEntries])
  const totalDebtNdt = supplierRows.reduce((sum, row) => sum + row.remainingNdt, 0); const totalDebtVnd = supplierRows.reduce((sum, row) => sum + row.remainingVnd, 0); const selected = supplierRows.find(row => row.supplier.supplierId === supplierId)
  const saveSupplier = () => { const debt = parseNumber(openingDebt); const exchangeRate = parseNumber(rate); if (!name.trim()) return setError('Nhập tên nhà cung cấp.'); if (debt < 0 || exchangeRate <= 0) return setError('Nhập dư nợ và tỷ giá hợp lệ.'); const supplier = addSupplier({ name, openingDebtNdt: debt, exchangeRate }); setSupplierId(supplier.supplierId); setName(''); setOpeningDebt(''); setRate(String(settings.exchangeRate)); setShowSupplierForm(false); setError('') }
  const savePayment = () => { const ndt = parseNumber(paymentNdt); if (!selected) return setError('Chọn nhà cung cấp cần trả.'); if (!ndt || ndt < 0) return setError('Nhập số tiền tệ cần trả hợp lệ.'); if (ndt > selected.remainingNdt) return setError(`NCC này chỉ còn nợ ${selected.remainingNdt.toLocaleString('vi-VN', { maximumFractionDigits: 2 })} tệ.`); const amount = Math.round(ndt * selected.supplier.exchangeRate); addPayment({ supplierId, amountNdt: ndt, exchangeRate: selected.supplier.exchangeRate, amount, paymentDate: todayIso(), note: note.trim() }); setPaymentNdt(''); setNote(''); setShowPaymentForm(false); setError('') }
  const saveDebtEntry = () => { const ndt = parseNumber(debtNdt); const supplier = suppliers.find(item => item.supplierId === supplierId); if (!supplier) return setError('Chọn nhà cung cấp cần ghi nợ.'); if (!ndt || ndt < 0) return setError('Nhập số tiền nợ mới hợp lệ.'); addDebtEntry({ supplierId, amountNdt: ndt, exchangeRate: supplier.exchangeRate, debtDate: todayIso(), note: debtNote.trim() }); setDebtNdt(''); setDebtNote(''); setShowDebtForm(false); setError('') }
  return <><PageHeader title="Nhà nợ TQ" subtitle="Quản lý công nợ nhà cung cấp Trung Quốc" />
    <div className="metric-grid"><article className="metric-card supplier-debt-card"><span>Tổng nợ TQ</span><strong>{formatVnd(totalDebtVnd)}</strong><small>{totalDebtNdt.toLocaleString('vi-VN', { maximumFractionDigits: 2 })} tệ</small></article><article className="metric-card"><span>Khách còn nợ</span><strong>{formatVnd(customerDebt)}</strong></article></div>
    <div className="supplier-actions"><button className="secondary-button" onClick={() => { setShowSupplierForm(!showSupplierForm); setError('') }}>+ Thêm nhà cung cấp</button><button className="secondary-button" onClick={() => { setShowDebtForm(!showDebtForm); setError('') }} disabled={!suppliers.length}>+ Thêm nợ mới</button><button className="primary-button" onClick={() => { setShowPaymentForm(!showPaymentForm); setError('') }} disabled={!supplierRows.some(row => row.remainingNdt > 0)}>Xác nhận trả NCC</button></div>
    {showSupplierForm && <section className="form-card payment-form"><div className="form-card-heading"><h2>Nhà cung cấp TQ mới</h2></div><label className="field"><span className="field-label">Tên nhà cung cấp</span><input value={name} onChange={event => setName(event.target.value)} placeholder="Ví dụ: Xưởng Quảng Châu" /></label><label className="field"><span className="field-label">Dư nợ ban đầu (tệ)</span><input type="number" min={0} inputMode="decimal" value={openingDebt} onChange={event => setOpeningDebt(event.target.value)} /></label><label className="field"><span className="field-label">Tỷ giá riêng (VNĐ / tệ)</span><input type="number" min={1} inputMode="numeric" value={rate} onChange={event => setRate(event.target.value)} /></label>{error && <div className="error-banner">{error}</div>}<button className="primary-button" onClick={saveSupplier}>Lưu nhà cung cấp</button></section>}
    {showDebtForm && <section className="form-card payment-form"><div className="form-card-heading"><h2>Phát sinh nợ NCC</h2></div><label className="field"><span className="field-label">Nhà cung cấp</span><select value={supplierId} onChange={event => setSupplierId(event.target.value)}><option value="">Chọn nhà cung cấp</option>{suppliers.map(supplier => <option key={supplier.supplierId} value={supplier.supplierId}>{supplier.name}</option>)}</select></label><label className="field"><span className="field-label">Khoản nợ mới (tệ)</span><input type="number" min={0} inputMode="decimal" value={debtNdt} onChange={event => setDebtNdt(event.target.value)} /></label>{suppliers.find(item => item.supplierId === supplierId) && <div className="cash-help">Quy đổi: <strong>{formatVnd(parseNumber(debtNdt || '0') * (suppliers.find(item => item.supplierId === supplierId)?.exchangeRate ?? 0))}</strong></div>}<label className="field"><span className="field-label">Ghi chú</span><input value={debtNote} onChange={event => setDebtNote(event.target.value)} placeholder="Ví dụ: Đợt hàng tháng 9" /></label>{error && <div className="error-banner">{error}</div>}<button className="primary-button" onClick={saveDebtEntry}>Lưu khoản nợ mới</button></section>}
    {showPaymentForm && <section className="form-card payment-form"><div className="form-card-heading"><h2>Xác nhận trả NCC</h2></div><label className="field"><span className="field-label">Nhà cung cấp</span><select value={supplierId} onChange={event => setSupplierId(event.target.value)}><option value="">Chọn nhà cung cấp</option>{supplierRows.filter(row => row.remainingNdt > 0).map(row => <option key={row.supplier.supplierId} value={row.supplier.supplierId}>{row.supplier.name} · còn {row.remainingNdt.toLocaleString('vi-VN')} tệ</option>)}</select></label><label className="field"><span className="field-label">Số tiền trả (tệ)</span><input type="number" min={0} inputMode="decimal" value={paymentNdt} onChange={event => setPaymentNdt(event.target.value)} /></label>{selected && <div className="cash-help">Quy đổi: <strong>{formatVnd(parseNumber(paymentNdt || '0') * selected.supplier.exchangeRate)}</strong></div>}<label className="field"><span className="field-label">Ghi chú</span><input value={note} onChange={event => setNote(event.target.value)} placeholder="Nội dung thanh toán" /></label>{error && <div className="error-banner">{error}</div>}<button className="primary-button" onClick={savePayment}>Xác nhận trả NCC</button></section>}
    <section className="form-card"><div className="form-card-heading"><h2>Danh sách Nhà cung cấp TQ</h2><span>{suppliers.length} NCC</span></div>{supplierRows.map(row => <div className="supplier-row" key={row.supplier.supplierId}><div><strong>{row.supplier.name}</strong><span>Tỷ giá: {formatVnd(row.supplier.exchangeRate)} / tệ</span><span>Nợ lịch sử: {row.supplier.openingDebtNdt.toLocaleString('vi-VN')} tệ · Phát sinh: {row.addedNdt.toLocaleString('vi-VN', { maximumFractionDigits: 2 })} tệ · Đã trả: {row.paidNdt.toLocaleString('vi-VN', { maximumFractionDigits: 2 })} tệ</span></div><div className="supplier-row-actions"><strong className={row.remainingNdt > 0 ? 'debt' : 'settled'}>{row.remainingNdt.toLocaleString('vi-VN', { maximumFractionDigits: 2 })} tệ<br /><small>{formatVnd(row.remainingVnd)}</small></strong></div></div>)}{!suppliers.length && <div className="empty-state"><strong>Chưa có nhà cung cấp</strong><p>Thêm NCC để theo dõi dư nợ theo tệ và VNĐ.</p></div>}</section>
  </>
}
