import { useMemo, useState } from 'react'
import { DeleteSupplierConfirmModal } from '../components/DeleteSupplierConfirmModal'
import { PageHeader } from '../components/PageHeader'
import { useCustomerDebts } from '../hooks/useCustomerDebts'
import { useInvoices } from '../hooks/useInvoices'
import { useOperatingExpenses } from '../hooks/useOperatingExpenses'
import { useSettings } from '../hooks/useSettings'
import { useSupplierPayments } from '../hooks/useSupplierPayments'
import type { ChinaSupplier } from '../types/invoice'
import { todayIso } from '../utils/id'
import { formatVnd, parseNumber } from '../utils/money'

export function SupplierDebtPage() {
  const { settings } = useSettings(); const { invoices } = useInvoices(); const { expenses } = useOperatingExpenses(); const { debts } = useCustomerDebts()
  const { suppliers, payments, addSupplier, addPayment, deleteSupplier } = useSupplierPayments()
  const [showSupplierForm, setShowSupplierForm] = useState(false); const [showPaymentForm, setShowPaymentForm] = useState(false); const [name, setName] = useState(''); const [openingDebt, setOpeningDebt] = useState(''); const [rate, setRate] = useState(String(settings.exchangeRate)); const [supplierId, setSupplierId] = useState(''); const [paymentNdt, setPaymentNdt] = useState(''); const [note, setNote] = useState(''); const [error, setError] = useState(''); const [supplierToDelete, setSupplierToDelete] = useState<ChinaSupplier | null>(null)
  const summary = useMemo(() => { const active = invoices.filter(invoice => invoice.status !== 'bombed'); const profit = (invoice: typeof active[number]) => invoice.profit ?? invoice.subtotal - (invoice.chinaCostTotal || 0) - (invoice.operatingCostTotal || 0) - (invoice.itemOperatingCostTotal || 0); const totalProfit = active.reduce((sum, invoice) => sum + profit(invoice), 0) - expenses.reduce((sum, expense) => sum + expense.total, 0); const uncollected = active.reduce((sum, invoice) => sum + (invoice.subtotal > 0 ? profit(invoice) * Math.min(1, Math.max(0, invoice.remaining / invoice.subtotal)) : 0), 0); const supplierPaid = payments.reduce((sum, payment) => sum + payment.amount, 0); const customerDebt = active.reduce((sum, invoice) => sum + invoice.remaining, 0) + debts.reduce((sum, debt) => sum + debt.remaining, 0); const actualProfit = totalProfit - uncollected; return { actualProfit, supplierPaid, availableCash: Math.max(0, actualProfit - supplierPaid), customerDebt } }, [invoices, expenses, debts, payments])
  const supplierRows = useMemo(() => suppliers.map(supplier => { const mine = payments.filter(payment => payment.supplierId === supplier.supplierId); const paidNdt = mine.reduce((sum, payment) => sum + (payment.amountNdt ?? payment.amount / (payment.exchangeRate || supplier.exchangeRate)), 0); const remainingNdt = Math.max(0, supplier.openingDebtNdt - paidNdt); return { supplier, paidNdt, remainingNdt, remainingVnd: remainingNdt * supplier.exchangeRate } }), [suppliers, payments])
  const totalDebtNdt = supplierRows.reduce((sum, row) => sum + row.remainingNdt, 0); const totalDebtVnd = supplierRows.reduce((sum, row) => sum + row.remainingVnd, 0); const selected = supplierRows.find(row => row.supplier.supplierId === supplierId)
  const saveSupplier = () => { const debt = parseNumber(openingDebt); const exchangeRate = parseNumber(rate); if (!name.trim()) return setError('Nhập tên nhà cung cấp.'); if (debt < 0 || exchangeRate <= 0) return setError('Nhập dư nợ và tỷ giá hợp lệ.'); const supplier = addSupplier({ name, openingDebtNdt: debt, exchangeRate }); setSupplierId(supplier.supplierId); setName(''); setOpeningDebt(''); setRate(String(settings.exchangeRate)); setShowSupplierForm(false); setError('') }
  const savePayment = () => { const ndt = parseNumber(paymentNdt); if (!selected) return setError('Chọn nhà cung cấp cần trả.'); if (!ndt || ndt < 0) return setError('Nhập số tiền tệ cần trả hợp lệ.'); if (ndt > selected.remainingNdt) return setError(`NCC này chỉ còn nợ ${selected.remainingNdt.toLocaleString('vi-VN', { maximumFractionDigits: 2 })} tệ.`); const amount = Math.round(ndt * selected.supplier.exchangeRate); if (amount > summary.availableCash) return setError(`Tiền mặt khả dụng chỉ còn ${formatVnd(summary.availableCash)}.`); addPayment({ supplierId, amountNdt: ndt, exchangeRate: selected.supplier.exchangeRate, amount, paymentDate: todayIso(), note: note.trim() }); setPaymentNdt(''); setNote(''); setShowPaymentForm(false); setError('') }
  const removeSupplier = () => { if (!supplierToDelete) return; const id = supplierToDelete.supplierId; deleteSupplier(id); if (supplierId === id) { setSupplierId(''); setPaymentNdt(''); setNote(''); setShowPaymentForm(false) }; setSupplierToDelete(null); setError('') }
  return <><PageHeader title="Nhà nợ TQ" subtitle="Quản lý công nợ NCC theo tệ và dòng tiền thực tế" />
    <div className="metric-grid"><article className="metric-card supplier-debt-card"><span>Tổng nợ NCC TQ</span><strong>{formatVnd(totalDebtVnd)}</strong><small>{totalDebtNdt.toLocaleString('vi-VN', { maximumFractionDigits: 2 })} tệ</small></article><article className="metric-card"><span>Lợi nhuận thực tế</span><strong>{formatVnd(summary.actualProfit)}</strong></article><article className="metric-card cash-available-card"><span>Tiền mặt khả dụng</span><strong>{formatVnd(summary.availableCash)}</strong></article><article className="metric-card"><span>Đã trả NCC TQ</span><strong>{formatVnd(summary.supplierPaid)}</strong></article><article className="metric-card"><span>Khách còn nợ</span><strong>{formatVnd(summary.customerDebt)}</strong></article></div>
    <div className="supplier-actions"><button className="secondary-button" onClick={() => { setShowSupplierForm(!showSupplierForm); setError('') }}>+ Thêm nhà cung cấp</button><button className="primary-button" onClick={() => { setShowPaymentForm(!showPaymentForm); setError('') }} disabled={!suppliers.length || summary.availableCash <= 0}>Xác nhận trả NCC</button></div>
    {showSupplierForm && <section className="form-card payment-form"><div className="form-card-heading"><h2>Nhà cung cấp TQ mới</h2></div><label className="field"><span className="field-label">Tên nhà cung cấp</span><input value={name} onChange={event => setName(event.target.value)} placeholder="Ví dụ: Xưởng Quảng Châu" /></label><label className="field"><span className="field-label">Dư nợ ban đầu (tệ)</span><input type="number" min={0} inputMode="decimal" value={openingDebt} onChange={event => setOpeningDebt(event.target.value)} /></label><label className="field"><span className="field-label">Tỷ giá riêng (VNĐ / tệ)</span><input type="number" min={1} inputMode="numeric" value={rate} onChange={event => setRate(event.target.value)} /></label>{error && <div className="error-banner">{error}</div>}<button className="primary-button" onClick={saveSupplier}>Lưu nhà cung cấp</button></section>}
    {showPaymentForm && <section className="form-card payment-form"><div className="form-card-heading"><h2>Xác nhận trả NCC</h2></div><label className="field"><span className="field-label">Nhà cung cấp</span><select value={supplierId} onChange={event => setSupplierId(event.target.value)}><option value="">Chọn nhà cung cấp</option>{supplierRows.filter(row => row.remainingNdt > 0).map(row => <option key={row.supplier.supplierId} value={row.supplier.supplierId}>{row.supplier.name} · còn {row.remainingNdt.toLocaleString('vi-VN')} tệ</option>)}</select></label><label className="field"><span className="field-label">Số tiền trả (tệ)</span><input type="number" min={0} inputMode="decimal" value={paymentNdt} onChange={event => setPaymentNdt(event.target.value)} /></label>{selected && <div className="cash-help">Quy đổi: <strong>{formatVnd(parseNumber(paymentNdt || '0') * selected.supplier.exchangeRate)}</strong></div>}<label className="field"><span className="field-label">Ghi chú</span><input value={note} onChange={event => setNote(event.target.value)} placeholder="Nội dung thanh toán" /></label>{error && <div className="error-banner">{error}</div>}<button className="primary-button" onClick={savePayment}>Xác nhận trả NCC</button></section>}
    <section className="form-card"><div className="form-card-heading"><h2>Danh sách Nhà cung cấp TQ</h2><span>{suppliers.length} NCC</span></div>{supplierRows.map(row => <div className="supplier-row" key={row.supplier.supplierId}><div><strong>{row.supplier.name}</strong><span>Tỷ giá: {formatVnd(row.supplier.exchangeRate)} / tệ</span><span>Nợ gốc: {row.supplier.openingDebtNdt.toLocaleString('vi-VN')} tệ · Đã trả: {row.paidNdt.toLocaleString('vi-VN', { maximumFractionDigits: 2 })} tệ</span></div><div className="supplier-row-actions"><strong className={row.remainingNdt > 0 ? 'debt' : 'settled'}>{row.remainingNdt.toLocaleString('vi-VN', { maximumFractionDigits: 2 })} tệ<br /><small>{formatVnd(row.remainingVnd)}</small></strong><button className="list-delete-button" onClick={() => setSupplierToDelete(row.supplier)} aria-label={`Xóa nhà cung cấp ${row.supplier.name}`}>Xóa</button></div></div>)}{!suppliers.length && <div className="empty-state"><strong>Chưa có nhà cung cấp</strong><p>Thêm NCC để theo dõi dư nợ theo tệ và VNĐ.</p></div>}</section>
    <section className="form-card"><div className="form-card-heading"><h2>Lịch sử thanh toán NCC</h2></div>{[...payments].sort((a, b) => b.paymentDate.localeCompare(a.paymentDate) || b.createdAt.localeCompare(a.createdAt)).map(payment => <div className="invoice-line" key={payment.paymentId}><div><strong>{suppliers.find(supplier => supplier.supplierId === payment.supplierId)?.name || 'Thanh toán NCC cũ'}</strong><span>{new Date(payment.createdAt).toLocaleString('vi-VN')}{payment.amountNdt ? ` · ${payment.amountNdt.toLocaleString('vi-VN')} tệ` : ''}{payment.note ? ` · ${payment.note}` : ''}</span></div><strong>{formatVnd(payment.amount)}</strong></div>)}{!payments.length && <div className="empty-state"><strong>Chưa có khoản trả NCC</strong><p>Lịch sử trả nợ sẽ lưu cả thời gian giao dịch thực tế.</p></div>}</section>
    {supplierToDelete && <DeleteSupplierConfirmModal supplier={supplierToDelete} paymentCount={payments.filter(payment => payment.supplierId === supplierToDelete.supplierId).length} onCancel={() => setSupplierToDelete(null)} onConfirm={removeSupplier} />}
  </>
}
